Repository dnsimple/bugsnag-erlang, pull requests merged in 2025-02, with the labels that each got.

#22 Updates bugsnag documentation link
  src/bugsnag.erl
Labels: enhancement

#21 Update README.md
  README.md
Labels: enhancement

#24 feat: added customer encoder using OTP27 json
  src/bugsnag.erl
Labels: bug, enhancement

#25 Requires markdownlint-cli & yamllint to pass in CI before test
  .github/workflows/ci.yml
Labels: enhancement

#26 Bumps to v2.0.1
  CHANGELOG.md
  src/bugsnag.erl
  src/bugsnag_erlang.app.src
Labels: task
